### ISSUE TITLE
eBay API URI inconsistencies causing problems with sandbox

### ISSUE THREAD

**Issue by gbm001** [matecsaj/ebay_rest#1]
Firstly, thanks for writing this! I am trying to implement it, although my needs are probably slightly different as I am working on a web-based app so I have to get my credentials and refresh token in another way and then hack them while creating the API instance... (also I have to replace _refresh_user in Token, since I need to get an access code from a stored refresh token rather then running through the whole authorization process again, but then you should probably do that too...)

Anyway, I am trying to use the Finances API, and that has API endpoints of the form apiz.ebay.com and apiz.sandbox.ebay.com, which means the replacement of 'api.ebay.com' with 'api.sandbox.ebay.com' in _get_swagger_method in a_p_i.py (line 367) doesn't work; you probably need to match 'apiz.ebay.com' as well?

Thanks again :) hopefully I can contribute something back to this project.

**Comment by matecsaj** [comment]
As it happens, I am currently reworking user token management. So please answer a few questions so that I can better understand your needs. 

1. Do you have one set of application credentials and multiple sets of user credentials? 

2. Instead of storing credentials in ebay_rest.json, do you want to supply parameters when instantiating an API object?

3. Outside of ebay_rest, do you want to acquire a user token and then supply it to ebay_rest as a parameter when instantiating an API object?

Which calls within the Finances API do you plan to use? Perhaps I will add one to the unit tests to provide a working example for you and others.

Posting issues is one way to contribute to the project, and thanks for being the first to do that! I'm still learning about GitHub best practices. I've noticed that some projects make issues for each contribution opportunity. Do you recommend this or some other approach to making it easier for others to get involved?

**Comment by gbm001** [comment]
Hi,

1) I have one set of application credentials (app ID, dev ID, cert ID, RU name) and one set of user credentials personally (this app is only used by our company); more specifically, I acquire through my app a refresh token for production and sandbox (which are of course different eBay accounts, so technically I guess I do have multiple users).
2) We use ebay_sdk for the trading API side, so previously we have stored credentials in the ebay.yaml file it uses, but that's not as convenient for the OAuth APIs where you need to go through the authorization flow to get a refresh token, so being able to supply these when instantiating the API object would be more convenient (in my current testing I have them stored in the database).
3) Yes (in fact I am already doing that, and dropping it into ebay_rest via some hackery setting the attributes, tokens, scopes etc. in the Token class, and monkey-patching _refresh_user for now although I'm assuming it will all evolve so this is temporary).

I think it would be good to be able to pass a refresh token (together with the matching scopes(?) and RU name) to the API, and have that be persistent in Token (or CredentialUtil).

We are trying to get access to the Finances API (sell_finances), so I've been trying to play with get_transactions. I did briefly get it working in the sandbox (with a lot of hackery); there are issues with user_access_token being set wrong by the process_api_cache script. I'm trying to work out how to fix it. I think it is a pain since Swagger only seems to import one thing from the components/securitySchemes in the JSON which doesn't really help, so will have to be something like what you do with base_path to get it from the JSON and then doing it manually. I think you need to look at what scope each call is making and then choose the appropriate authentication?
