### ISSUE TITLE
Bugs in the eBay JSON contract

### ISSUE THREAD

**Issue by gbm001** [matecsaj/ebay_rest#16]
This isn't actually a bug in ebay_rest but in the OpenAPI 3 JSON contract eBay provides.

In the Sell Fulfillment API, the model 'Address' is returned with attribute 'countryCode'. However, the JSON specifies 'country' instead, thus Swagger generates the wrong API. I had to manually patch 'country' to 'country_code' (or 'countryCode' as appropriate) which is quite annoying.

I don't know if there's a simple way of auto-patching these things; obviously it would be easier to just get eBay to fix them (the error is not in the OpenAPI 2 contract, just the v3) but my posts on the developer forum have disappeared into 'your post is awaiting moderation'...

**Comment by matecsaj** [comment]
Since we can't control what eBay does, and other things like this might crop up, we should write some patching code.

One approach would be to cache the contracts to local storage and patch them before use.  In the file 'generate_api_cache.py,' immediately after the line 'contracts = get_contracts(limit=300)', I would add calls to a couple of new methods and then tweak anything that currently directly downloads contracts.

Do you have a solution in the works, or should I take this on?

**Comment by gbm001** [comment]
I have not done anything to do with patching the eBay contracts (other than have thoughts along the same lines as you); I was rather hoping I could get eBay to fix it but I my hopes are fading...

**Comment by matecsaj** [comment]
[Resolved.](https://github.com/matecsaj/ebay_rest/commit/91a8b036e831013f348dcd921dea6cca9f822b6c)

**Comment by gbm001** [comment]
Awesome thanks :)
