### ISSUE TITLE
Unit tests have a resource warning.

### ISSUE THREAD

**Issue by matecsaj** [matecsaj/ebay_rest#5]
Several times in tests/ebay_rest.py, the following lines appear. 

# TODO Stop ignoring the warning and remedy the resource leak.

warnings.filterwarnings(action="ignore", message="unclosed", category=ResourceWarning)

Please remove the lines and fix the underlying problem.

**Comment by gbm001** [comment]
I think you only get the warning in the unit tests because warnings are more turned on in the unit tests than in 'normal' execution. However, I couldn't find the issue when I had a quick look. I also get errors when closing down a terminal that I've used ebay_rest in. I suspect the problem is not important, but probably still worth giving another look...

**Comment by matecsaj** [comment]
I tried again with no success. [A warning about the problem will now show once, and only once when all unit tests are run.](https://github.com/matecsaj/ebay_rest/commit/0f2f4d391a8d9a3771a30c35cb31b5275e693a4d)

**Comment by matecsaj** [comment]
This is no longer a problem, so warning suppression will be removed from today's code.
